apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mlops-puj-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/miguelhzuniga/mlops-repo.git
    targetRevision: master
    path: Taller_CICD/manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false