apiVersion: apps/v1
kind: Deployment
metadata:
  name: gradio-housing
  namespace: gradio  
  labels:
    app: gradio-housing
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gradio-housing
  template:
    metadata:
      labels:
        app: gradio-housing
    spec:
      containers:
      - name: gradio-housing
        image: luisfrontuso10/gradio-houses:20250602-6d2228e
        ports:
        - containerPort: 8501
        env:
        - name: MLFLOW_S3_ENDPOINT_URL
          value: "http://minio.mlflow.svc.cluster.local:9000"  
        - name: AWS_ACCESS_KEY_ID
          value: "adminuser"
        - name: AWS_SECRET_ACCESS_KEY
          value: "securepassword123"
        - name: MLFLOW_TRACKING_URI
          value: "http://mlflow.mlflow.svc.cluster.local:5000"  
        resources:
          requests:
            memory: "512Mi"
            cpu: "200m"
          limits:
            memory: "1Gi"
            cpu: "500m"