apiVersion: v1
kind: Service
metadata:
  name: gradio-housing-service
  namespace: mlops-project
spec:
  type: NodePort
  selector:
    app: gradio-housing
  ports:
    - port: 8501
      targetPort: 8501
      nodePort: 30602