apiVersion: apps/v1
kind: Deployment
metadata:
  name: gradio-housing
  namespace: mlops-project
  labels:
    app: gradio-housing
spec:
  replicas: 3
  selector:
    matchLabels:
      app: gradio-housing
  template:
    metadata:
      labels:
        app: gradio-housing
    spec:
      restartPolicy: Always
      containers:
      - name: gradio-housing
        image: luisfrontuso10/gradio-houses:20250603-afef697
        imagePullPolicy: Always
        ports:
        - containerPort: 8501
        livenessProbe:
          httpGet:
            path: /
            port: 8501
          initialDelaySeconds: 60
          periodSeconds: 60
          timeoutSeconds: 10
          failureThreshold: 10
          successThreshold: 1
        readinessProbe:
          httpGet:
            path: /
            port: 8501
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 10
          successThreshold: 1
        env:
        - name: MLFLOW_S3_ENDPOINT_URL
          value: "http://10.43.101.175:30382"
        - name: AWS_ACCESS_KEY_ID
          value: "adminuser"
        - name: AWS_SECRET_ACCESS_KEY
          value: "securepassword123"
        - name: MLFLOW_TRACKING_URI
          value: "http://10.43.101.175:30500"
        resources:
          requests:
            memory: "512Mi"
            cpu: "200m"
          limits:
            memory: "1Gi"
            cpu: "500m"