apiVersion: v1
kind: Namespace
metadata:
  name: gradio
---
apiVersion: v1
kind: Service
metadata:
  name: gradio-service
  namespace: gradio
  labels:
    app: gradio-housing
spec:
  selector:
    app: gradio-housing
  ports:
  - port: 8501
    targetPort: 8501
    nodePort: 30851
  type: NodePort
