apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-service-NOAM38
  namespace: mlops-project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: example-service-NOAM38
  template:
    metadata:
      labels:
        app: example-service-NOAM38
    spec:
      nodeSelector:
        node-id: NOAM38
      containers:
      - name: nginx
        image: nginx
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "200m"
---
apiVersion: v1
kind: Service
metadata:
  name: example-service-NOAM38
  namespace: mlops-project
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30080
  selector:
    app: example-service-NOAM38
