apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-diabetes
  namespace: mlops-project
  labels:
    app: fastapi-diabetes
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fastapi-diabetes
  template:
    metadata:
      labels:
        app: fastapi-diabetes
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
        prometheus.io/port: "8000"
    spec:
      containers:
      - name: fastapi-diabetes
        image: ${YOUR_REGISTRY}/fastapi-diabetes:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        env:
        - name: MLFLOW_TRACKING_URI
          value: "http://${MLFLOW_NODE_IP}:30500"
        - name: AWS_ACCESS_KEY_ID
          value: adminuser
        - name: AWS_SECRET_ACCESS_KEY
          value: securepassword123
        - name: MLFLOW_S3_ENDPOINT_URL
          value: "http://${MINIO_NODE_IP}:9000"
        resources:
          requests:
            memory: "512Mi"
            cpu: "200m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 15
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: fastapi-service
  namespace: mlops-project
spec:
  type: NodePort
  ports:
  - port: 8000
    targetPort: 8000
    nodePort: 30501
  selector:
    app: fastapi-diabetes