scheduler:
  replicas: 1
  resources:
    requests:
      cpu: 200m
      memory: 1Gi
    limits:
      cpu: 1000m
      memory: 2Gi

webserver:
  replicas: 1
  service:
    type: NodePort
    nodePort:
      http: 32080  
  resources:
    requests:
      cpu: 200m
      memory: 1Gi
    limits:
      cpu: 1000m
      memory: 2Gi

workers:
  replicas: 2
  resources:
    requests:
      cpu: 200m
      memory: 1Gi
    limits:
      cpu: 1000m
      memory: 2Gi

postgresql:
  enabled: true
  auth:
    enablePostgresUser: true
    postgresPassword: "airflow123"
    username: "airflow"
    password: "airflow123"
    database: "airflow"
  primary:
    persistence:
      enabled: true
      size: 8Gi
      storageClass: "microk8s-hostpath"

redis:
  enabled: true
  auth:
    enabled: false
  master:
    persistence:
      enabled: true
      size: 5Gi
      storageClass: "microk8s-hostpath"

executor: "CeleryExecutor"

dags:
  gitSync:
    enabled: true
    repo: "https://github.com/ftuga/dags_airflow_kubernete.git"
    branch: "main"
    rev: "HEAD"
    depth: 1
    maxFailures: 0
    subPath: "dags"
    wait: 60
    containerName: git-sync
    uid: 65533

logs:
  persistence:
    enabled: true
    size: 10Gi
    storageClass: "microk8s-hostpath"

env:
  - name: AIRFLOW__CORE__LOAD_EXAMPLES
    value: "False"
  - name: AIRFLOW__WEBSERVER__AUTHENTICATE
    value: "False"
  - name: AIRFLOW__CORE__DEFAULT_TIMEZONE
    value: "America/Bogota"
  - name: MLFLOW_TRACKING_URI
    value: "http://mlflow.mlops-project.svc.cluster.local:5000"
  - name: MLFLOW_S3_ENDPOINT_URL
    value: "http://minio.mlops-project.svc.cluster.local:9000"
  - name: AWS_ACCESS_KEY_ID
    value: "adminuser"
  - name: AWS_SECRET_ACCESS_KEY
    value: "securepassword123"

config:
  core:
    dags_are_paused_at_creation: 'False'
    load_examples: 'False'
  webserver:
    authenticate: False
    expose_config: True
  scheduler:
    dag_dir_list_interval: 30


serviceAccount:
  create: true
  name: "airflow"

images:
  airflow:
    repository: camilosvel/airflow-diabetes  
    tag: latest                             
    pullPolicy: Always                      

webserverSecretKey: "airflow-secret-key"
createUserJob:
  useHelmHooks: false