apiVersion: v1
kind: ConfigMap
metadata:
  name: pgadmin-config
  namespace: mlops-project
data:
  servers.json: |
    {
      "Servers": {
        "1": {
          "Name": "Airflow PostgreSQL",
          "Group": "MLOps",
          "Host": "airflow-postgresql.mlops-project.svc.cluster.local",
          "Port": 5432,
          "MaintenanceDB": "airflow",
          "Username": "airflow",
          "SSLMode": "prefer",
          "SSLCert": "<STORAGE_DIR>/.postgresql/postgresql.crt",
          "SSLKey": "<STORAGE_DIR>/.postgresql/postgresql.key",
          "SSLCompression": 0,
          "Timeout": 10,
          "UseSSHTunnel": 0,
          "TunnelPort": "22",
          "TunnelAuthentication": 0
        },
        "2": {
          "Name": "MLflow PostgreSQL",
          "Group": "MLOps",
          "Host": "postgres.mlops-project.svc.cluster.local",
          "Port": 5432,
          "MaintenanceDB": "mlflow",
          "Username": "mlflow",
          "SSLMode": "prefer",
          "SSLCert": "<STORAGE_DIR>/.postgresql/postgresql.crt",
          "SSLKey": "<STORAGE_DIR>/.postgresql/postgresql.key",
          "SSLCompression": 0,
          "Timeout": 10,
          "UseSSHTunnel": 0,
          "TunnelPort": "22",
          "TunnelAuthentication": 0
        }
      }
    }

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgadmin
  namespace: mlops-project
  labels:
    app: pgadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pgadmin
  template:
    metadata:
      labels:
        app: pgadmin
    spec:
      containers:
      - name: pgadmin
        image: dpage/pgadmin4:latest 
        env:
        - name: PGADMIN_DEFAULT_EMAIL
          value: "admin@example.com"
        - name: PGADMIN_DEFAULT_PASSWORD
          value: "admin"
        - name: PGADMIN_CONFIG_SERVER_MODE
          value: "False"
        - name: PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED
          value: "False"
        ports:
        - containerPort: 80
        volumeMounts:
        - name: pgadmin-config
          mountPath: /pgadmin4/servers.json
          subPath: servers.json
          readOnly: true
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi
      volumes:
      - name: pgadmin-config
        configMap:
          name: pgadmin-config

---
apiVersion: v1
kind: Service
metadata:
  name: pgadmin
  namespace: mlops-project
  labels:
    app: pgadmin
spec:
  selector:
    app: pgadmin
  ports:
  - name: http
    port: 80
    targetPort: 80
    nodePort: 30050
  type: NodePort