executor: "CeleryExecutor"

images:
  airflow:
    repository: airflow-custom
    tag: latest
    pullPolicy: Never

dags:
  gitSync:
    enabled: true
    repo: https://github.com/ftuga/dags_airflow_kubernete.git
    branch: main
    rev: HEAD
    depth: 1
    maxFailures: 0
    subPath: "dags"
    wait: 60
    containerName: git-sync
    uid: 65533

data:
  metadataConnection:
    user: airflow
    pass: airflow123
    protocol: postgresql
    host: airflow-postgresql.mlops-project
    port: 5432
    db: airflow

webserver:
  service:
    type: NodePort
    ports:
      - name: airflow-ui
        port: 8080
        nodePort: 30080
  defaultUser:
    enabled: true
    username: airflow
    password: airflow

postgresql:
  enabled: true
  auth:
    enablePostgresUser: true
    postgresPassword: "airflow123"
    username: "airflow"
    password: "airflow123"
    database: "airflow"
  persistence:
    enabled: true
    size: 8Gi
    storageClass: "microk8s-hostpath"

redis:
  enabled: true

env:
  - name: MLFLOW_TRACKING_URI
    value: "http://mlflow.mlops-project.svc.cluster.local:5000"
  - name: MLFLOW_S3_ENDPOINT_URL
    value: "http://minio.mlops-project.svc.cluster.local:9000"
  - name: AWS_ACCESS_KEY_ID
    value: "adminuser"
  - name: AWS_SECRET_ACCESS_KEY
    value: "securepassword123"