services:
  
  locust:
    build:
      context: ./locust
      dockerfile: Dockerfile.locust
    #container_name: locust
    ports:
      - "8089-8092:8089"
    environment:
      - LOCUST_HOST=http://10.43.101.175:8000
    deploy:
      mode: replicated
      replicas: 4
      resources:
        limits:
          memory: 2500M
          cpus: 0.125
    restart: "no"
