services:
  
  locust:
    build:
      context: ./locust
      dockerfile: Dockerfile.locust
    #container_name: locust
    ports:
      - "8089-8090:8089"
    environment:
      - LOCUST_HOST=http://10.43.101.175:8000
    # networks:
    #   - net_mlops  
    deploy:
      mode: replicated
      replicas: 2
      resources:
        limits:
          memory: 10000M
          cpus: 4
    restart: "no"
