apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mlflow-app
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: mlflow=luisfrontuso10/mlflow-houses:latest
    argocd-image-updater.argoproj.io/mlflow.update-strategy: latest
spec:
  project: default
  source:
    repoURL: https://github.com/miguelhzuniga/mlops-repo.git
    targetRevision: HEAD
    path: proyecto-04/01_Primera_maquina/mlflow/manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: mlops-project
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true