apiVersion: v1
kind: Service
metadata:
  name: fastapi-housing-service
  namespace: mlops-project
spec:
  type: NodePort
  selector:
    app: fastapi-housing
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30601