apiVersion: v1
kind: Namespace
metadata:
  name: fastapi
---
apiVersion: v1
kind: Service
metadata:
  name: fastapi-service
  namespace: fastapi
  labels:
    app: fastapi-housing
spec:
  selector:
    app: fastapi-housing
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30800
  type: NodePort