apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-housing
  namespace: mlops-project
  labels:
    app: fastapi-housing
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fastapi-housing
  template:
    metadata:
      labels:
        app: fastapi-housing
    spec:
      containers:
      - name: fastapi-housing

        image: luisfrontuso10/fastapi-houses:20250602-f4b3d38
        ports:
        - containerPort: 80
        env:
        - name: MLFLOW_S3_ENDPOINT_URL
          value: "http://10.43.101.175:30382"
        - name: AWS_ACCESS_KEY_ID
          value: "adminuser"
        - name: AWS_SECRET_ACCESS_KEY
          value: "securepassword123"
        - name: MLFLOW_TRACKING_URI
          value: "http://10.43.101.175:30500"
        resources:
          requests:
            memory: "512Mi"
            cpu: "200m"
          limits:
            memory: "1Gi"
            cpu: "500m"