apiVersion: v1
kind: Service
metadata:
  name: airflow-webserver
  namespace: mlops
spec:
  selector:
    app: airflow-webserver
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30080
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-airflow
  namespace: mlops
spec:
  selector:
    app: postgres-airflow
  ports:
  - port: 5432
    targetPort: 5432
  type: ClusterIP