feature {
  name: "Hillshade_9am"
  type: INT
  int_domain {
    min: 0
    max: 255
  }
}
feature {
  name: "Hillshade_Noon"
  type: INT
  int_domain {
    min: 0
    max: 255
  }
}
feature {
  name: "Slope"
  type: INT
  int_domain {
    min: 0
    max: 90
  }
}
feature {
  name: "Cover_Type"
  type: INT
  int_domain {
    min: 0
    max: 6
  }
}
