apiVersion: apps/v1
kind: Deployment
metadata:
  name: locust
  namespace: mlops-project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: locust
  template:
    metadata:
      labels:
        app: locust
    spec:
      containers:
      - name: locust
        image: locustio/locust
        args:
          - -f
          - /mnt/locust/locustfile.py
          - --host=http://fastapi-service.mlops-project.svc.cluster.local:8000
          - --web-host=0.0.0.0
        ports:
        - containerPort: 8089
        volumeMounts:
        - name: locust-script
          mountPath: /mnt/locust
      volumes:
      - name: locust-script
        configMap:
          name: locust-script
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: locust-script
  namespace: mlops-project
data:
  locustfile.py: |
    from locust import HttpUser, task, between

    class APITestUser(HttpUser):
        wait_time = between(1, 3)

        @task
        def predict(self):
            self.client.post("/predict", json={"feature1": 1.0, "feature2": 2.0})
---
apiVersion: v1
kind: Service
metadata:
  name: locust
  namespace: mlops-project
spec:
  type: NodePort
  selector:
    app: locust
  ports:
  - port: 8089
    targetPort: 8089
    nodePort: 31000
