apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - api-deployment.yaml
  - script-deployment.yaml
  - prometheus-deployment.yaml
  - grafana-deployment.yaml

namespace: mlops-puj

images:
  - name: luisfrontuso10/ml-api
    newName: luisfrontuso10/ml-api
    newTag: latest
  - name: luisfrontuso10/locust
    newName: luisfrontuso10/locust
    newTag: latest