apiVersion: apps/v1
kind: Deployment
metadata:
  name: locust
  namespace: mlops-puj
spec:
  replicas: 1
  selector:
    matchLabels:
      app: locust
  template:
    metadata:
      labels:
        app: locust
    spec:
      containers:
      - name: locust
        image: luisfrontuso10/locust:latest
        ports:
        - containerPort: 8089
        env:
        - name: API_HOST
          value: "ml-api-service"
        - name: API_PORT
          value: "8000"
---
apiVersion: v1
kind: Service
metadata:
  name: locust-service
  namespace: mlops-puj
spec:
  type: NodePort
  selector:
    app: locust
  ports:
    - port: 8089
      targetPort: 8089
      nodePort: 30089
