global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'ml-api'
    scrape_interval: 5s
    metrics_path: /metrics
    static_configs:
      - targets: ['10.43.101.202:30623']