apiVersion: apps/v1
kind: Deployment
metadata:
  name: load-tester
  labels:
    app: load-tester
spec:
  replicas: 1
  selector:
    matchLabels:
      app: load-tester
  template:
    metadata:
      labels:
        app: load-tester
    spec:
      containers:
      - name: load-tester
        image: ${DOCKER_USERNAME}/load-tester:${IMAGE_TAG}
        env:
        - name: API_HOST
          value: "ml-api-service"
        - name: API_PORT
          value: "8000"
        - name: REQUEST_INTERVAL
          value: "1.0"
        resources:
          limits:
            cpu: "200m"
            memory: "256Mi"
          requests:
            cpu: "100m"
            memory: "128Mi"