apiVersion: batch/v1
kind: Job
metadata:
  name: minio-init
  namespace: mlops-project
spec:
  template:
    spec:
      containers:
      - name: mc
        image: minio/mc
        command: ["/bin/sh", "-c"]
        args:
        - |
          sleep 10;
          mc config host add myminio http://minio:30900 adminuser securepassword123;
          mc mb myminio/mlflow-artifacts --ignore-existing;
          mc anonymous set download myminio/mlflow-artifacts;
          echo "MinIO bucket created successfully";
      restartPolicy: Never
  backoffLimit: 4