apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlflow
  namespace: mlops-project  
spec:
  replicas: 3
  progressDeadlineSeconds: 900
  selector:
    matchLabels:
      app: mlflow
  template:
    metadata:
      labels:
        app: mlflow
    spec:
      restartPolicy: Always
      containers:
      - name: mlflow
        image: luisfrontuso10/mlflow-houses:20250603-635b84c
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        livenessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 120
          periodSeconds: 60
          timeoutSeconds: 15
          failureThreshold: 10
          successThreshold: 1
        readinessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 15
          failureThreshold: 10
          successThreshold: 1
        env:
        - name: MLFLOW_S3_ENDPOINT_URL
          value: http://minio.mlops-project.svc.cluster.local:9000
        - name: AWS_ACCESS_KEY_ID
          value: adminuser
        - name: AWS_SECRET_ACCESS_KEY
          value: securepassword123
        command:
        - sh
        - -c
        - |
          echo "Esperando 20 segundos para que los servicios estén listos..."
          sleep 20
          
          echo "Iniciando MLflow server..."
          mlflow server \
            --backend-store-uri postgresql://mlflow:mlflow123@postgres.mlops-project.svc.cluster.local:5432/mlflow \
            --default-artifact-root s3://mlflow-artifacts/ \
            --host 0.0.0.0 \
            --port 5000
        resources:
          requests:
            memory: "512Mi"
            cpu: "200m"
          limits:
            memory: "1Gi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: mlflow
  namespace: mlops-project  
spec:
  selector:
    app: mlflow
  ports:
  - port: 5000
    targetPort: 5000
    nodePort: 30500
  type: NodePort