apiVersion: v1
kind: Service
metadata:
  name: fastapi-diabetes-service
  namespace: mlops-project
spec:
  type: NodePort
  selector:
    app: fastapi-diabetes
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30601