<<<<<<< HEAD
<<<<<<< HEAD
=======
<<<<<<< HEAD
version: '3.8'

services:
  jupyter-lab:
    build:
      context: .
      dockerfile: Dockerfile.jupyter
    ports:
      - "8888:8888"  
    volumes:
      - ./notebooks:/home/jovyan/work/notebooks  
      - ./data:/home/jovyan/work/data
=======
version: '3'  # Especifica la versión de Docker Compose que se está utilizando.

services:     # Define los servicios que se ejecutarán en contenedores Docker.
  ml_service: # Nombre del servicio, en este caso es un servicio para ML (Machine Learning).
    build: .  # Indica que Docker debe construir la imagen usando el Dockerfile ubicado en el directorio actual (".").
    
=======
>>>>>>> master
version: '3'
services:
  api:
    build: ./api
>>>>>>> 89aec48b56334c813e340b0f7c4271d5a76975ab
    ports:
      - "8000:80"
    volumes:
      - './api:/api'
      - ./train:/train
    command: ["uvicorn", "main-app:app", "--host", "0.0.0.0", "--port", "80"]
  jupyterlab:
    build: ./train
    container_name: jupyterlab
    working_dir: /train
    volumes:
      - ./train:/train
    ports:
      - "8888:8888"
<<<<<<< HEAD
=======
version: '3.8'

services:
  jupyter-lab:
    build:
      context: .
      dockerfile: Dockerfile.jupyter
    ports:
      - "8888:8888"  
    volumes:
<<<<<<< HEAD
<<<<<<< HEAD
      - ./notebooks:/home/jovyan/work/notebooks  
>>>>>>> 0f16ff7 (taller 2)
=======
      - ./notebooks:/home/jovyan/work/notebooks  
>>>>>>> b466687 (ajuste docker)
=======
      - ./notebooks:/home/jovyan/work/notebooks  
      - ./data:/home/jovyan/work/data
>>>>>>> 613d8d0 (ajuste de notebook)
=======
<<<<<<< HEAD
    command: ["python","-m","jupyter", "lab", "--ip=0.0.0.0", "--port=8888", "--allow-root"]
>>>>>>> 53364723d38940547937c499141372a8beadfc9b
=======
>>>>>>> 89aec48b56334c813e340b0f7c4271d5a76975ab
>>>>>>> master
