<<<<<<< HEAD
version: '3'
services:
  api:
    build: ./api
    ports:
      - "8000:80"
    volumes:
      - './api:/api'
      - ./train:/train
    command: ["uvicorn", "main-app:app", "--host", "0.0.0.0", "--port", "80"]
  jupyterlab:
    build: ./train
    container_name: jupyterlab
    working_dir: /train
    volumes:
      - ./train:/train
    ports:
      - "8888:8888"
=======
version: '3.8'

services:
  jupyter-lab:
    build:
      context: .
      dockerfile: Dockerfile.jupyter
    ports:
      - "8888:8888"  
    volumes:
<<<<<<< HEAD
      - ./notebooks:/home/jovyan/work/notebooks  
>>>>>>> 0f16ff7 (taller 2)
=======
      - ./notebooks:/home/jovyan/work/notebooks  
>>>>>>> b466687 (ajuste docker)
