apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  namespace: mlops-puj
data:
  datasources.yaml: |
    apiVersion: 1
    datasources:
    - name: Prometheus
      type: prometheus
      url: http://prometheus-service:9090
      access: proxy
      isDefault: true