services:
  minio:
    image: quay.io/minio/minio:latest
    container_name: Minio
    restart: unless-stopped
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=supersecret
    ports:
      - "9000:9000"  # MinIO S3 en localhost
      - "9001:9001"  # Consola web en localhost
    command: server /data --console-address ":9001"
    volumes:
      - ./minio:/data

  postgres:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: experiments
    ports:
      - "5432:5432"
    command: ["postgres", "-c", "listen_addresses=*"]
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

fastapi:
  image: python:3.9
  container_name: fastapi
  environment:
    DATABASE_URL: postgresql://user:password@localhost:5432/experiments
    MLFLOW_TRACKING_URI: http://10.43.101.175:5000
  ports:
    - "8000:8000"
  volumes:
    - ./api:/app
  working_dir: /app
  network_mode: "host"
  command: >
    bash -c "
    apt-get update && apt-get install -y --no-install-recommends curl ca-certificates &&
    curl -sSL https://astral.sh/uv/install.sh | sh &&
    export PATH=\"/root/.local/bin/:$PATH\" &&
    pip install fastapi uvicorn==0.27.0.post1 mlflow==2.0.1 pandas pydantic scikit-learn dill python-multipart requests &&
    uvicorn app.main-app:app --host 0.0.0.0 --port 8000"



  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
